name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.412+8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List target directory
      run: ls -la ./target

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: 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
      with:
        tag_name: v0.5
        release_name: Release v0.5
        draft: false
        prerelease: false

    - name: Upload release artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/RedisBungee-0.5.jar
        asset_name: RedisBungee-0.5.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: 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
